### ISSUE TITLE
confidence value

### ISSUE THREAD

**Issue by isspek** [co-inform/coinform-content-analysis#37]
Hey @rdenaux 

My models is based on sckit-learn and i noticed that by calling predict_proba i am already retrieving confidence-values for each class. 

Here is the [code](https://github.com/co-inform/coinform-content-analysis/blob/master/src/estimators/baseline.py)

Probabilities could be treated directly by confidence. Max value of these confidence values will be already label of the prediction. 

I would be appreciated if you check my code in the link, and tell me what you would like to see exactly.

**Comment by rdenaux** [comment]
I suspected this was the case, because it looks like `veracity_true + veracity_false + veracity_unknown = 1.0`. But it'd be nice to have a formula for converting your output to credibility (between -1 and 1) and confidence (between 0 and 1). 

I think something like this may work:

``` python
cred_sum = veracity_true + veracity_false
winner = veracity_true if veracity_trye > veraticy_false else veracity_false
polarity = 1 if veracity_true > veracity_false else -1
cred = polarity * winner/cred_sum
conf = 1 - veracity_unknown
```
but it's your model, so you should tell us whether this makes sense or not.

**Comment by isspek** [comment]
This makes sense for me, I added the competition, now it maps
